// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoContests.Entities;

#nullable disable

namespace PhotoContests.Migrations
{
    [DbContext(typeof(PhotoContestsContext))]
    partial class PhotoContestsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PhotoContests.Entities.Assignement", b =>
                {
                    b.Property<string>("idUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("idCompetition")
                        .HasColumnType("int");

                    b.Property<DateTime>("assignementDate")
                        .HasColumnType("datetime2");

                    b.HasKey("idUser", "idCompetition");

                    b.HasIndex("idCompetition");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("PhotoContests.Entities.Competition", b =>
                {
                    b.Property<int>("idCompetition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCompetition"));

                    b.Property<DateTime?>("datePhotoTakenLimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("idType")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("photosLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("resultsDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("urlPosterPhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCompetition");

                    b.HasIndex("idType");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("PhotoContests.Entities.Message", b =>
                {
                    b.Property<int>("idMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMessage"));

                    b.Property<string>("idUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("idUser2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("messageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("sendDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("visibility")
                        .HasColumnType("bit");

                    b.HasKey("idMessage");

                    b.HasIndex("idUser");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PhotoContests.Entities.Nationality", b =>
                {
                    b.Property<int>("idNationality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idNationality"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idNationality");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("PhotoContests.Entities.Notification", b =>
                {
                    b.Property<int>("idNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idNotification"));

                    b.Property<string>("idUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("idUser2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("sendDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idNotification");

                    b.HasIndex("idUser");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PhotoContests.Entities.Participation", b =>
                {
                    b.Property<int>("idPhoto")
                        .HasColumnType("int");

                    b.Property<int>("idCompetition")
                        .HasColumnType("int");

                    b.Property<int>("idSection")
                        .HasColumnType("int");

                    b.Property<double>("finalResult")
                        .HasColumnType("float");

                    b.Property<int>("ranking")
                        .HasColumnType("int");

                    b.Property<string>("reportMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("totalPoints")
                        .HasColumnType("int");

                    b.HasKey("idPhoto", "idCompetition", "idSection");

                    b.HasIndex("idCompetition");

                    b.HasIndex("idSection");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("PhotoContests.Entities.Photo", b =>
                {
                    b.Property<int>("idPhoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPhoto"));

                    b.Property<string>("cameraModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("downloadTime")
                        .HasColumnType("datetime2");

                    b.Property<float?>("exposureTime")
                        .HasColumnType("real");

                    b.Property<float?>("fStop")
                        .HasColumnType("real");

                    b.Property<string>("idUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("isoSpeed")
                        .HasColumnType("int");

                    b.Property<string>("photoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("takenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("visibility")
                        .HasColumnType("bit");

                    b.HasKey("idPhoto");

                    b.HasIndex("idUser");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("PhotoContests.Entities.Report", b =>
                {
                    b.Property<int>("idReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idReport"));

                    b.Property<int>("idCompetition")
                        .HasColumnType("int");

                    b.Property<int>("idPhoto")
                        .HasColumnType("int");

                    b.Property<int>("idSection")
                        .HasColumnType("int");

                    b.Property<string>("idUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("noAccept")
                        .HasColumnType("int");

                    b.Property<int>("noDecline")
                        .HasColumnType("int");

                    b.HasKey("idReport");

                    b.HasIndex("idUser");

                    b.HasIndex("idPhoto", "idCompetition", "idSection");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("PhotoContests.Entities.Review", b =>
                {
                    b.Property<int>("idReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idReview"));

                    b.Property<int>("idCompetition")
                        .HasColumnType("int");

                    b.Property<int>("idPhoto")
                        .HasColumnType("int");

                    b.Property<int>("idSection")
                        .HasColumnType("int");

                    b.Property<string>("idUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("sendDate")
                        .HasColumnType("datetime2");

                    b.HasKey("idReview");

                    b.HasIndex("idUser");

                    b.HasIndex("idPhoto", "idCompetition", "idSection");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PhotoContests.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("PhotoContests.Entities.Section", b =>
                {
                    b.Property<int>("idSection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSection"));

                    b.Property<string>("detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("minimumAge")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("presentationUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("presentationYTCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSection");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("PhotoContests.Entities.Type", b =>
                {
                    b.Property<int>("idType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idType"));

                    b.Property<string>("competitionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idType");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("PhotoContests.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("availability")
                        .HasColumnType("bit");

                    b.Property<string>("biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("connectionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("newsSubscription")
                        .HasColumnType("bit");

                    b.Property<string>("profilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PhotoContests.Entities.UserRoles", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("PhotoContests.Entities.Video", b =>
                {
                    b.Property<int>("idVideo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVideo"));

                    b.Property<string>("JurorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCompetition")
                        .HasColumnType("int");

                    b.Property<int>("idPhoto")
                        .HasColumnType("int");

                    b.Property<int>("idSection")
                        .HasColumnType("int");

                    b.Property<string>("videoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoYTCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idVideo");

                    b.HasIndex("JurorId");

                    b.HasIndex("idPhoto", "idCompetition", "idSection")
                        .IsUnique();

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("PhotoContests.Entities.Voting", b =>
                {
                    b.Property<int>("idVoting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVoting"));

                    b.Property<int>("idCompetition")
                        .HasColumnType("int");

                    b.Property<int>("idPhoto")
                        .HasColumnType("int");

                    b.Property<int>("idSection")
                        .HasColumnType("int");

                    b.Property<string>("idUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("jurorVote")
                        .HasColumnType("int");

                    b.Property<int>("publicVote")
                        .HasColumnType("int");

                    b.HasKey("idVoting");

                    b.HasIndex("idUser");

                    b.HasIndex("idPhoto", "idCompetition", "idSection");

                    b.ToTable("Votings");
                });

            modelBuilder.Entity("PhotoContests.Entities.Juror", b =>
                {
                    b.HasBaseType("PhotoContests.Entities.User");

                    b.Property<int>("yearsOfExperience")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Juror");
                });

            modelBuilder.Entity("PhotoContests.Entities.Photographer", b =>
                {
                    b.HasBaseType("PhotoContests.Entities.User");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("idNationality")
                        .HasColumnType("int");

                    b.HasIndex("idNationality");

                    b.HasDiscriminator().HasValue("Photographer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("PhotoContests.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PhotoContests.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PhotoContests.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PhotoContests.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhotoContests.Entities.Assignement", b =>
                {
                    b.HasOne("PhotoContests.Entities.Competition", "Competition")
                        .WithMany("Assignements")
                        .HasForeignKey("idCompetition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoContests.Entities.Juror", "Juror")
                        .WithMany("Assignements")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Juror");
                });

            modelBuilder.Entity("PhotoContests.Entities.Competition", b =>
                {
                    b.HasOne("PhotoContests.Entities.Type", "Type")
                        .WithMany("Competitions")
                        .HasForeignKey("idType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PhotoContests.Entities.Message", b =>
                {
                    b.HasOne("PhotoContests.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhotoContests.Entities.Notification", b =>
                {
                    b.HasOne("PhotoContests.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhotoContests.Entities.Participation", b =>
                {
                    b.HasOne("PhotoContests.Entities.Competition", "Competition")
                        .WithMany("Participations")
                        .HasForeignKey("idCompetition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoContests.Entities.Photo", "Photo")
                        .WithMany("Participations")
                        .HasForeignKey("idPhoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoContests.Entities.Section", "Section")
                        .WithMany("Participations")
                        .HasForeignKey("idSection")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Photo");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("PhotoContests.Entities.Photo", b =>
                {
                    b.HasOne("PhotoContests.Entities.Photographer", "Photographer")
                        .WithMany("Photos")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photographer");
                });

            modelBuilder.Entity("PhotoContests.Entities.Report", b =>
                {
                    b.HasOne("PhotoContests.Entities.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoContests.Entities.Participation", "Participation")
                        .WithMany("Reports")
                        .HasForeignKey("idPhoto", "idCompetition", "idSection")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Participation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhotoContests.Entities.Review", b =>
                {
                    b.HasOne("PhotoContests.Entities.Juror", "Juror")
                        .WithMany("Reviews")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoContests.Entities.Participation", "Participation")
                        .WithMany("Reviews")
                        .HasForeignKey("idPhoto", "idCompetition", "idSection")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Juror");

                    b.Navigation("Participation");
                });

            modelBuilder.Entity("PhotoContests.Entities.UserRoles", b =>
                {
                    b.HasOne("PhotoContests.Entities.Role", "Role")
                        .WithMany("UsersRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoContests.Entities.User", "User")
                        .WithMany("UsersRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhotoContests.Entities.Video", b =>
                {
                    b.HasOne("PhotoContests.Entities.Juror", "Juror")
                        .WithMany("Videos")
                        .HasForeignKey("JurorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoContests.Entities.Participation", "Participation")
                        .WithOne("Video")
                        .HasForeignKey("PhotoContests.Entities.Video", "idPhoto", "idCompetition", "idSection")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Juror");

                    b.Navigation("Participation");
                });

            modelBuilder.Entity("PhotoContests.Entities.Voting", b =>
                {
                    b.HasOne("PhotoContests.Entities.User", "User")
                        .WithMany("Votings")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoContests.Entities.Participation", "Participation")
                        .WithMany("Votings")
                        .HasForeignKey("idPhoto", "idCompetition", "idSection")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Participation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhotoContests.Entities.Photographer", b =>
                {
                    b.HasOne("PhotoContests.Entities.Nationality", "Nationality")
                        .WithMany("Photographers")
                        .HasForeignKey("idNationality")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("PhotoContests.Entities.Competition", b =>
                {
                    b.Navigation("Assignements");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("PhotoContests.Entities.Nationality", b =>
                {
                    b.Navigation("Photographers");
                });

            modelBuilder.Entity("PhotoContests.Entities.Participation", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("Reviews");

                    b.Navigation("Video")
                        .IsRequired();

                    b.Navigation("Votings");
                });

            modelBuilder.Entity("PhotoContests.Entities.Photo", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("PhotoContests.Entities.Role", b =>
                {
                    b.Navigation("UsersRoles");
                });

            modelBuilder.Entity("PhotoContests.Entities.Section", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("PhotoContests.Entities.Type", b =>
                {
                    b.Navigation("Competitions");
                });

            modelBuilder.Entity("PhotoContests.Entities.User", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Reports");

                    b.Navigation("UsersRoles");

                    b.Navigation("Votings");
                });

            modelBuilder.Entity("PhotoContests.Entities.Juror", b =>
                {
                    b.Navigation("Assignements");

                    b.Navigation("Reviews");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("PhotoContests.Entities.Photographer", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
